### ISSUE TITLE
Lecture: Requirements Documentation - Date: 17th September, 2024

### ISSUE THREAD

**Issue by harshc22** [harshc22/ML-Herd-Management#1]
**Requirements Documentation**

**September 17th, 2024**

**Attendance**

- [x] Aryan Patel
- [x] Harsh Chinjer
- [x] Krish Patel
- [x] Martin Ivanov
- [x] Shazim Rahman

**Questions to Ask**

-

**Comment by ShazimR** [comment]
Closing since there are no tasks or questions to ask
