### ISSUE TITLE
TA Meeting - Date October 7th, 2024

### ISSUE THREAD

**Issue by harshc22** [harshc22/ML-Herd-Management#25]
**Purpose of Meeting**: SRS Informal Presentation

**Date and Time**: Oct 7th, 2024 | 4:00 pm - 4:15 pm

**Attendance**

- [x] Aryan Patel
- [x] Harshpreet Chinjer
- [x] Krish Patel
- [x] Martin Ivanov
- [ ] Shazim Rahman

**Questions to Ask**

- What is the difference between Legal Requirements and Standards Compliance Requirements
- What terminology should be define for section 4? So far ML, IoT, but what about sire and dam?  
- How do we track the version numbering for this document? update it for each PR or just 1.0 for the entire document?

**Comment by KrishPatel27** [comment]
* What is the difference between Legal Requirements and Standards Compliance Requirements

Legal pertains to the law. Compliance pertains to standards that are followed, but are necessarily followed. 

* What terminology should be define for section 4? So far ML, IoT, but what about sire and dam?
Uncommon terminology should be included as well as acronyms used. 

* How do we track the version numbering for this document? update it for each PR or just 1.0 for the entire document?
 This portion is up to the user. Increment the versioning if it feels that the version needs to be incremented. The version number of the document does not pertain to the Rev0 and Rev1 terminology used. 


Additional Questions asked during the presentation: 
* What should we do if there is no information to place in a section? 
Include the section and state that there is no information for it yet. 

* What should we include for section 26?
List some common ML models we could use.
