### ISSUE TITLE
Supervisor Meeting - October 25, 2024

### ISSUE THREAD

**Issue by harshc22** [harshc22/ML-Herd-Management#55]
**Date and Time**
October 25th at 3:15 pm

**Attendance**

- [x] Aryan Patel
- [x] Harshpreet Chinjer
- [x] Krish Patel
- [x] Martin Ivanov
- [x] Shazim Rahman

**Agenda**

- Meeting with leading genetics expert Mehdi Sargolzaei to learn more about cattle genetics and find the best outcome for the project.

**Questions to Ask**

- In your opinion, what traits should we be trying to predict based off of the mother and sire traits? We were thinking lameness, milk production, breeding success, and herd retention for instance.
- We want to get an idea of which mother and sire traits have the most influence and should be prioritized in our model.
- Are there any common genetic markers or indicators in dairy cattle that signal desirable or undesirable traits?
- Do you have any advice for us regarding the data preprocessing? 
- How do you recommend we handle incomplete or missing data? 
- Are there genetic traits that are prone to misinterpretation or false positives that we should be aware of?

This one is more just for our understanding and to get an expectation for how accurate our model could be:
- How significant are non-genetic factors (like the environment and how the cattle are managed) compared to genetic factors in trait prediction?

**Comment by harshc22** [comment]
# Meeting Notes

## Overview of Inbreeding Concerns in Animal Selection
- **Importance of Inbreeding Consideration**:  
  Inbreeding is a significant factor in animal selection as it can negatively impact fertility and reduce genetic diversity. Reduced diversity makes populations more vulnerable to diseases and environmental changes.  
  - **Objective**: Avoid excessive inbreeding to maintain a diverse and healthy herd.

## Key Concepts and Methods in Managing Inbreeding
- **Additive Model Selection**:  
  The additive model is used in selecting animals, where selection occurs for one gene at a time. This approach can help remove recessive genes responsible for certain illnesses, although it may inadvertently increase susceptibility to other diseases if diversity is too low.
  
- **Calculating Inbreeding**:  
  Inbreeding can be assessed through:
  1. **Common Ancestor Analysis**: Reviewing the family tree for shared ancestors.
  2. **Genomic Data Analysis**: Examining the genome data to calculate inbreeding levels, though currently, pedigree data is available while genomic data might still be lacking.

## Types of Inbreeding
- **Old Inbreeding**:  
  Generally less harmful as undesirable genes are more likely to be phased out over time.  
- **New Inbreeding**:  
  Higher risk due to a greater chance of harmful genes being inherited. This can lead to inbreeding depression, which manifests as reduced production, decreased health, and lower fitness of animals.

- **Inbreeding Depression**:  
  Accumulated inbreeding can lead to lower productivity and increased susceptibility to disease, affecting the overall fitness of the animal population.

## Genetic Diversity in Cattle
- **Low Diversity Challenge**:  
  With limited genetic diversity in cows, the risk of negative consequences from inbreeding is heightened. High milk production traits from popular sires (e.g., bulls like Sundance and Icecube) make them widely used, which decreases diversity across herds.
  - **Recommendation**: To counterbalance, using multiple sires rather than relying heavily on a few popular bulls helps maintain diversity.

## Data Requirements and AI Application
- **Third-Party Data and Sire Lineage**:  
  Data collection directly from farmers provides approximately 50% of the needed information. Including data from sires is essential to get a complete genetic picture.
- **AI Pattern Analysis**:  
  By leveraging AI, patterns in genetic selection and inbreeding can be identified to better understand factors contributing to decreased milk production.

- **Available Resources**:
  - **Pedigree Data**: Available and can be utilized for lineage and inbreeding tracking.
  - **Genomic Data**: Not yet accessible but could enhance accuracy if included.
  - **Inbreeding Calculation Software**:
    - **Lactanet** and **Canadian Food Control (CFC)** can be employed to help calculate inbreeding metrics.

## Inbreeding Tolerance Levels
- **Acceptable Inbreeding Levels**:  
  Determining acceptable inbreeding percentages is complex:
  - **Environmental Influence**: Animals in harsh conditions have a lower tolerance to inbreeding, while those in well-maintained environments can handle slightly higher levels.
  - **Threshold**: Generally, around 30-40% is considered acceptable in breeding programs, though specific thresholds depend on health and environmental factors.

## Example from CFC Software
- In analyzing pedigree data, for instance, **Animal J** might show a lineage path `<E <B> F>`, where `E` and `F` are the parents of `J` and `B` is a common ancestor. This path structure aids in identifying shared ancestry and calculating inbreeding.

**Comment by ShazimR** [comment]
The meeting was completed and all meeting notes have been attached. Closing.
