### ISSUE TITLE
TA Meeting - October 28th, 2024

### ISSUE THREAD

**Issue by harshc22** [harshc22/ML-Herd-Management#60]
**Purpose of Meeting**
Informal VnV Plan Presentation 

**Date and Time**
October 28th, 2024 at 2:30 pm

**Attendance**

- [x] Aryan Patel
- [x] Harshpreet Chinjer
- [x] Krish Patel
- [x] Martin Ivanov
- [x] Shazim Rahman

**Questions to Ask**

- Do we need a validation plan to ensure the software complies with the legal requirements specified in SRS (PIPEDA and the Code of Practice for the Care and Handling of Dairy Cattle)
- Since we are building an ML model, how do go about writing test cases?

**Comment by Aryanpatel335** [comment]
- Test cases can be made up right now, must related back to the NFR and FR that we have added in the SRS.
- Software validation -> Supervisor Dr VanDePol will be our tester as she is the end user and has detailed understanding of what must be done.

Krish:
Q: Every input might now have the same output, how do we determine if output is appropriate 
A: Define a range for the output.
